spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/monitoring_system?characterEncoding=utf-8&useSSL=false
    username: root
    password: CHENchen2011
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    favicon:
      enabled: false

server:
  port: 8081
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: SEUwlt
    key-store-type: PKCS12
    key-alias: hpgary


